language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl COVERALLS=true
    - LISP=ccl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  # Coveralls support
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls
  # Clone some libraries
  - git clone https://github.com/CommonDoc/common-doc.git ~/lisp/common-doc
  - git clone https://github.com/CommonDoc/common-doc-plump.git ~/lisp/common-doc-plump
  - git clone https://github.com/CommonDoc/common-html.git ~/lisp/common-html
  - git clone https://github.com/CommonDoc/vertex.git ~/lisp/vertex
  - git clone https://github.com/CommonDoc/scriba.git ~/lisp/scriba
  - git clone https://github.com/CommonDoc/parenml.git ~/lisp/parenml
  - git clone https://github.com/CommonDoc/pandocl.git ~/lisp/pandocl
  - git clone https://github.com/mmontone/djula.git ~/lisp/djula
  - git clone https://github.com/eudoxia0/docparser.git ~/lisp/docparser

script:
  - cl -l fiveam -l cl-coveralls
       -e '(setf fiveam:*debug-on-error* t
                 fiveam:*debug-on-failure* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(coveralls:with-coveralls (:exclude (list "t"))
             (ql:quickload :codex-test))'

notifications:
  email:
    - eudoxiahp@gmail.com
