language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  # Clone some libraries
  - git clone https://github.com/CommonDoc/common-doc.git ~/lisp/common-doc
  - git clone https://github.com/CommonDoc/common-doc-plump.git ~/lisp/common-doc-plump
  - git clone https://github.com/CommonDoc/common-html.git ~/lisp/common-html
  - git clone https://github.com/CommonDoc/vertex.git ~/lisp/vertex
  - git clone https://github.com/fukamachi/quickdocs.git ~/lisp/quickdocs
  - git clone https://github.com/mmontone/djula.git ~/lisp/djula

script:
  - cl -e '(ql:quickload :fiveam)'
       -e '(setf fiveam:*debug-on-error* t
                 fiveam:*debug-on-failure* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(ql:quickload :codex-test)'

notifications:
  email:
    - eudoxiahp@gmail.com
