language: common-lisp

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t
  matrix:
    - LISP=sbcl-bin COVERALLS=true

install:
  # Roswell & coveralls
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls
  # Clone some libraries
  - git clone https://github.com/CommonDoc/common-doc.git ~/lisp/common-doc
  - git clone https://github.com/CommonDoc/common-doc-plump.git ~/lisp/common-doc-plump
  - git clone https://github.com/CommonDoc/common-html.git ~/lisp/common-html
  - git clone https://github.com/CommonDoc/vertex.git ~/lisp/vertex
  - git clone https://github.com/CommonDoc/scriba.git ~/lisp/scriba
  - git clone https://github.com/CommonDoc/parenml.git ~/lisp/parenml
  - git clone https://github.com/CommonDoc/pandocl.git ~/lisp/pandocl
  - git clone https://github.com/mmontone/djula.git ~/lisp/djula
  - git clone https://github.com/eudoxia0/docparser.git ~/lisp/docparser

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

before_script:
  - ros --version
  - ros config

script:
  - ros -e '(ql:quickload (list :fiveam :cl-coveralls))'
        -e '(setf fiveam:*debug-on-error* t
                  fiveam:*debug-on-failure* t)'
        -e '(setf *debugger-hook*
                  (lambda (c h)
                    (declare (ignore c h))
                    (uiop:quit -1)))'
        -e '(coveralls:with-coveralls (:exclude (list "t" "src/error.lisp"))
              (ql:quickload :codex-templates)
              (ql:quickload :codex-test)
              (funcall
               (symbol-function
                (intern (symbol-name (quote :do-tests))
                        (find-package :codex-test)))))'
